# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apache:
      repo: puppetlabs/apache
      ref: 7.0.0
    archive:
      repo: puppet/archive
      ref: 6.0.2
    concat:
      repo: puppetlabs/concat
      ref: 7.1.1
    dockerinstall:
      repo: aursu/dockerinstall
      ref: 0.12.1
    inifile:
      repo: 'puppetlabs/inifile'
      ref: 5.2.0
    kmod:
      repo: 'camptocamp/kmod'
      ref: 2.5.0
    lvm:
      repo: 'puppetlabs/lvm'
      ref: 1.4.0
    mysql:
      repo: puppetlabs/mysql
      ref: 12.0.1
    rabbitmq:
      repo: puppet/rabbitmq
      ref: 11.1.0
    sshkeys_core:
      repo: puppetlabs/sshkeys_core
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: puppetlabs/stdlib
      ref: 8.1.0
    sysctl:
      repo: thias/sysctl
      ref: 1.0.7
    systemd:
      repo: camptocamp/systemd
      ref: 3.0.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
  repositories:
    lsys:
      repo: https://github.com/aursu/puppet-lsys.git
      ref: tags/v0.24.3
    openssh:
      repo: https://github.com/aursu/puppet-openssh.git
      ref: tags/v0.6.7
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
