# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "4.4.0"
    concat:
      repo: "puppetlabs/concat"
      ref: '6.2.0'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '4.1.0'
    kmod:
      repo: 'camptocamp/kmod'
      ref: '2.4.0'
    lvm:
      repo: 'puppetlabs/lvm'
      ref: '1.4.0'
    mysql:
      repo: "puppetlabs/mysql"
      ref: "10.3.0"
    rabbitmq:
      repo: "puppet/rabbitmq"
      ref: "10.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.2.0"
    sysctl:
      repo: "thias/sysctl"
      ref: "1.0.6"
  repositories:
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: "tags/1.0.6"
      puppet_version: ">= 6.0.0"
    apache:
      repo: https://github.com/aursu/puppetlabs-apache.git
      ref: "tags/v5.4.0-aursu.3"
